server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_db?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
