server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_db?createDatabaseIfNotExist=true
    username: root
    password: password

  data:
    redis:
      database: 0
      host: localhost
      port: 6379

  session:
    store-type: redis

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
